### ISSUE TITLE
Error in Pulse Pulse 40.2.3

### ISSUE THREAD

**Issue by orchetect** [pulsedownloader/pulse-issues#32]
Comment (optional):

Error:
```
UnhandledRejection Error: ENOENT, No such file or directory '/Volumes/SAMPLES/VST/Super Audio Cart/Update 1.0.2'
    at check (/Applications/Pulse.app/Contents/Resources/app.asar/node_modules/diskusage/index.js:23:21)
    at /Applications/Pulse.app/Contents/Resources/app.asar/node_modules/diskusage/index.js:10:5
    at new Promise (<anonymous>)
    at Object.exports.check (/Applications/Pulse.app/Contents/Resources/app.asar/node_modules/diskusage/index.js:9:10)
    at getFreeDiskSpaceViaDiskUsage (/Applications/Pulse.app/Contents/Resources/app.asar/dist/compiled/main/webpack:/pulse/src/main/utils/fs/getFreeDiskSpace.ts:33:1)
    at getFreeDiskSpace (/Applications/Pulse.app/Contents/Resources/app.asar/dist/compiled/main/webpack:/pulse/src/main/utils/fs/getFreeDiskSpace.ts:22:1)
    at DiskSpaceChecker.makeCheck (/Applications/Pulse.app/Contents/Resources/app.asar/dist/compiled/main/webpack:/pulse/src/main/install/utils/DiskSpaceChecker.ts:28:1)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

OS: macOS 10.15.7

**Comment by orchetect** [comment]
This error continually repeats while downloading a library update now. FWIW, this happened during the download after selecting 'Manual Download & Install' but not sure if it also happens during an automated library update.

The library is located on a dedicated non-system disk (APFS) that is ignoring permissions.

**Comment by megahertz** [comment]
There's a chance the issue is fixed in the latest build. It wasn't published yet, but you can find it there: https://c8q9x5e9.map2.ssl.hwcdn.net/Pulse-40.2.5.dmg

**Comment by orchetect** [comment]
Pulse update to 40.2.6 today and I tried this again. The same issue is still present.

```
UnhandledRejection Error: ENOENT, No such file or directory '/Volumes/SAMPLES/VST/ISW Shreddage 3 Archtop/Update 1.312'
    at check (/Applications/Pulse.app/Contents/Resources/app.asar/node_modules/diskusage/index.js:23:21)
    at /Applications/Pulse.app/Contents/Resources/app.asar/node_modules/diskusage/index.js:10:5
    at new Promise (<anonymous>)
    at Object.exports.check (/Applications/Pulse.app/Contents/Resources/app.asar/node_modules/diskusage/index.js:9:10)
    at getFreeDiskSpaceViaDiskUsage (/Applications/Pulse.app/Contents/Resources/app.asar/dist/compiled/main/webpack:/pulse/src/main/utils/fs/getFreeDiskSpace.ts:33:1)
    at getFreeDiskSpace (/Applications/Pulse.app/Contents/Resources/app.asar/dist/compiled/main/webpack:/pulse/src/main/utils/fs/getFreeDiskSpace.ts:22:1)
    at DiskSpaceChecker.makeCheck (/Applications/Pulse.app/Contents/Resources/app.asar/dist/compiled/main/webpack:/pulse/src/main/install/utils/DiskSpaceChecker.ts:28:1)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

**Comment by megahertz** [comment]
Thank you for the report, will check that in the beginning of the next week.

**Comment by megahertz** [comment]
Will be fixed in v40.2.8. I think it will be ready on this week.

**Comment by megahertz** [comment]
Thank you for details That's fixed in v40.2.8
https://c8q9x5e9.map2.ssl.hwcdn.net/Pulse%20Web%20Setup%2040.2.8.exe
